language: python
python:
- '3.5'
- '3.6'
- '3.7'
install:
- pip install --upgrade setuptools pip setuptools_scm
- pip install -r requirements.txt
- python3 ./setup.py bdist_wheel
- pip3 install --upgrade ./dist/*.whl
script: py.test --cov=antlr_ast
after_success: codecov
deploy:
  provider: pypi
  user: datacamp
  password:
    secure: XgR1FFi6xknnCmDfvtcTTlyiIINk30mi33td364W3uVGKw/fAc5J01tTwOwbauuYtSyWPCp6GzX4sMTl40m6wSB/dbCzZxb7PxDxtfQyBBXeBBIOuJeRfo5nm+u1M1X33qmT9aidcCAv23TW3NakjnCIeDiCn1Ga3xhiwP/11zfnfQfEZlMgoXi6XTZmqAQj5OnbFF1CYEcO5LSipfx+sdqndYwMGR3iVxwrApExlY96XXMv9MSZXiSPcSk+mpgbdElwRaHw2PN43o2G9R6IMsuTRFijA0TnKlmA73jsd+tP5oAVRngLtZnzAhe2YwlGdmojnd0PROOyd1moBzq0hU/WJYm1fM1ipBG/iVSRgV3CDljMvItx5B9TMjeKcOhisAx/SMw0XNdB3DsqyaMVhUB6fGNlSj0AlrGEULggD8xi+gsK4SRf4F2hfADZR8vLyIx1rrTnXaINqhEG4Vu64g0PyodhXVqiAwcKxDq2Y4ywmilHGh6f3R708hBeNKa87a6vcCB/DqevH+7X2a8bfWU+uDQLFb5yM6rtopeWYovvB7lLZI2zb/dVXr/QhUZryIafs3Vb+/5lawmtcgGhU8Fk6r/Q8vFTXwBiE//uOQrURiUVhF7YUgFeXwOwpvqwtVJmPMyirteo2DUTsxtnuRT8b9McSJC4wUx0wi+eHKo=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: datacamp/antlr-ast
  skip_upload_docs: true
